spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=zoo_management
    username: zoo
    password: manager
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
